spring.application.name=MResendizProgramacionNCapas


jwt.secret = u3b2uymfElF1PHk8XsxxZm3Iv1j5aqw9ACMJw0s2MMT

jwt.expiration = 1800
#1800000

#spring.activemq.broker-url=tcp://localhost:61616
#spring.activemq.user=admin
#spring.activemq.password=admin
#spring.activemq.packages.trust-all=true


spring.mail.host =smtp.gmail.com
spring.mail.port = 587
spring.mail.username = manuelresendiz19062003@gmail.com
spring.mail.password =bxqsrksdideajniy
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true
