spring.application.name=MResendizProgramacionNCapas


jwt.secret = u3b2uymfElF1PHk8XsxxZm3Iv1j5aqw9ACMJw0s2MMT

jwt.expiration = 1800000



spring.mail.host =smtp.gmail.com
spring.mail.pot = 587
spring.mail.username =
spring.mail.password =bxqs rksd idea jniy
spring.mail.propierties.mail.smtp.auth = true
spring.mail.propierties.mail.stmp.starttls.enable = true
